### PR TITLE
added gcd,lcm,decimal to binary recursive and iterative code in python

### PR DESCRIPTION
**Pull request by AmanDeep-21**

### CODE REVIEW

**Comment by lakshya125** [comment]
Star the repository if you found it helpful and to find it easily next year

**Comment by AmanDeep-21** [comment]
@lakshya125 please see the way of code, I had used recursive and iterative method, I wasn't aware that there is a PR related to gcd, therefore I created a program for it. Please remove the invalid tag. I'll write down another code.

**Comment by AmanDeep-21** [comment]
@lakshya125 please see my point, I've mailed you as well.

**Comment by AmanDeep-21** [comment]
Thank you @lakshya125 for seeing my point, I'm thankful.

**Pull request closed without merging**
